humann2_regroup_table --input Travel001_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel001_CAZy.tsv
humann2_regroup_table --input Travel002_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel002_CAZy.tsv
humann2_regroup_table --input Travel003_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel003_CAZy.tsv
humann2_regroup_table --input Travel004_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel004_CAZy.tsv
humann2_regroup_table --input Travel005_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel005_CAZy.tsv
humann2_regroup_table --input Travel006_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel006_CAZy.tsv
humann2_regroup_table --input Travel007_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel007_CAZy.tsv
humann2_regroup_table --input Travel008_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel008_CAZy.tsv
humann2_regroup_table --input Travel009_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel009_CAZy.tsv
humann2_regroup_table --input Travel010_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel010_CAZy.tsv
humann2_regroup_table --input Travel011_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel011_CAZy.tsv
humann2_regroup_table --input Travel012_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel012_CAZy.tsv
humann2_regroup_table --input Travel014_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel014_CAZy.tsv
humann2_regroup_table --input Travel015_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel015_CAZy.tsv
humann2_regroup_table --input Travel016_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel016_CAZy.tsv
humann2_regroup_table --input Travel017_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel017_CAZy.tsv
humann2_regroup_table --input Travel018_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel018_CAZy.tsv
humann2_regroup_table --input Travel019_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel019_CAZy.tsv
humann2_regroup_table --input Travel020_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel020_CAZy.tsv
humann2_regroup_table --input Travel021_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel021_CAZy.tsv
humann2_regroup_table --input Travel022_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel022_CAZy.tsv
humann2_regroup_table --input Travel023_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel023_CAZy.tsv
humann2_regroup_table --input Travel024_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel024_CAZy.tsv
humann2_regroup_table --input Travel025_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel025_CAZy.tsv
humann2_regroup_table --input Travel026_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel026_CAZy.tsv
humann2_regroup_table --input Travel027_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel027_CAZy.tsv
humann2_regroup_table --input Travel028_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel028_CAZy.tsv
humann2_regroup_table --input Travel030_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel030_CAZy.tsv
humann2_regroup_table --input Travel031_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel031_CAZy.tsv
humann2_regroup_table --input Travel033_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel033_CAZy.tsv
humann2_regroup_table --input Travel036_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel036_CAZy.tsv
humann2_regroup_table --input Travel037_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel037_CAZy.tsv
humann2_regroup_table --input Travel038_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel038_CAZy.tsv
humann2_regroup_table --input Travel039_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel039_CAZy.tsv
humann2_regroup_table --input Travel040_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel040_CAZy.tsv
humann2_regroup_table --input Travel041_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel041_CAZy.tsv
humann2_regroup_table --input Travel042_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel042_CAZy.tsv
humann2_regroup_table --input Travel043_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel043_CAZy.tsv
humann2_regroup_table --input Travel045_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel045_CAZy.tsv
humann2_regroup_table --input Travel046_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel046_CAZy.tsv
humann2_regroup_table --input Travel047_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel047_CAZy.tsv
humann2_regroup_table --input Travel048_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel048_CAZy.tsv
humann2_regroup_table --input Travel049_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel049_CAZy.tsv
humann2_regroup_table --input Travel050_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel050_CAZy.tsv
humann2_regroup_table --input Travel051_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel051_CAZy.tsv
humann2_regroup_table --input Travel052_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel052_CAZy.tsv
humann2_regroup_table --input Travel053_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel053_CAZy.tsv
humann2_regroup_table --input Travel054_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel054_CAZy.tsv
humann2_regroup_table --input Travel057_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel057_CAZy.tsv
humann2_regroup_table --input Travel058_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel058_CAZy.tsv
humann2_regroup_table --input Travel059_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel059_CAZy.tsv
humann2_regroup_table --input Travel060_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel060_CAZy.tsv
humann2_regroup_table --input Travel061_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel061_CAZy.tsv
humann2_regroup_table --input Travel062_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel062_CAZy.tsv
humann2_regroup_table --input Travel063_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel063_CAZy.tsv
humann2_regroup_table --input Travel064_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel064_CAZy.tsv
humann2_regroup_table --input Travel065_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel065_CAZy.tsv
humann2_regroup_table --input Travel066_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel066_CAZy.tsv
humann2_regroup_table --input Travel067_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel067_CAZy.tsv
humann2_regroup_table --input Travel068_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel068_CAZy.tsv
humann2_regroup_table --input Travel070_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel070_CAZy.tsv
humann2_regroup_table --input Travel071_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel071_CAZy.tsv
humann2_regroup_table --input Travel072_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel072_CAZy.tsv
humann2_regroup_table --input Travel073_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel073_CAZy.tsv
humann2_regroup_table --input Travel075_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel075_CAZy.tsv
humann2_regroup_table --input Travel076_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel076_CAZy.tsv
humann2_regroup_table --input Travel077_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel077_CAZy.tsv
humann2_regroup_table --input Travel078_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel078_CAZy.tsv
humann2_regroup_table --input Travel079_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel079_CAZy.tsv
humann2_regroup_table --input Travel080_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel080_CAZy.tsv
humann2_regroup_table --input Travel081_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel081_CAZy.tsv
humann2_regroup_table --input Travel082_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel082_CAZy.tsv
humann2_regroup_table --input Travel083_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel083_CAZy.tsv
humann2_regroup_table --input Travel084_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel084_CAZy.tsv
humann2_regroup_table --input Travel085_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel085_CAZy.tsv
humann2_regroup_table --input Travel086_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel086_CAZy.tsv
humann2_regroup_table --input Travel087_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel087_CAZy.tsv
humann2_regroup_table --input Travel088_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel088_CAZy.tsv
humann2_regroup_table --input Travel089_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel089_CAZy.tsv
humann2_regroup_table --input Travel090_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel090_CAZy.tsv
humann2_regroup_table --input Travel091_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel091_CAZy.tsv
humann2_regroup_table --input Travel092_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel092_CAZy.tsv
humann2_regroup_table --input Travel093_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel093_CAZy.tsv
humann2_regroup_table --input Travel095_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel095_CAZy.tsv
humann2_regroup_table --input Travel096_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel096_CAZy.tsv
humann2_regroup_table --input Travel097_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel097_CAZy.tsv
humann2_regroup_table --input Travel098_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel098_CAZy.tsv
humann2_regroup_table --input Travel099_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel099_CAZy.tsv
humann2_regroup_table --input Travel100_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel100_CAZy.tsv
humann2_regroup_table --input Travel101_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel101_CAZy.tsv
humann2_regroup_table --input Travel102_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel102_CAZy.tsv
humann2_regroup_table --input Travel103_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel103_CAZy.tsv
humann2_regroup_table --input Travel104_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel104_CAZy.tsv
humann2_regroup_table --input Travel105_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel105_CAZy.tsv
humann2_regroup_table --input Travel106_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel106_CAZy.tsv
humann2_regroup_table --input Travel107_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel107_CAZy.tsv
humann2_regroup_table --input Travel108_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel108_CAZy.tsv
humann2_regroup_table --input Travel109_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel109_CAZy.tsv
humann2_regroup_table --input Travel110_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel110_CAZy.tsv
humann2_regroup_table --input Travel111_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel111_CAZy.tsv
humann2_regroup_table --input Travel112_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel112_CAZy.tsv
humann2_regroup_table --input Travel113_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel113_CAZy.tsv
humann2_regroup_table --input Travel114_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel114_CAZy.tsv
humann2_regroup_table --input Travel115_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel115_CAZy.tsv
humann2_regroup_table --input Travel117_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel117_CAZy.tsv
humann2_regroup_table --input Travel118_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel118_CAZy.tsv
humann2_regroup_table --input Travel119_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel119_CAZy.tsv
humann2_regroup_table --input Travel120_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel120_CAZy.tsv
humann2_regroup_table --input Travel121_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel121_CAZy.tsv
humann2_regroup_table --input Travel122_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel122_CAZy.tsv
humann2_regroup_table --input Travel123_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel123_CAZy.tsv
humann2_regroup_table --input Travel124_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel124_CAZy.tsv
humann2_regroup_table --input Travel125_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel125_CAZy.tsv
humann2_regroup_table --input Travel126_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel126_CAZy.tsv
humann2_regroup_table --input Travel131_genefamilies.tsv --custom CAZy_Custom_Mapping.txt --output Travel131_CAZy.tsv
