humann2_renorm_table --input Travel001_CAZy.tsv -u relab --output Travel001_CAZy_relab.tsv
humann2_renorm_table --input Travel002_CAZy.tsv -u relab --output Travel002_CAZy_relab.tsv
humann2_renorm_table --input Travel003_CAZy.tsv -u relab --output Travel003_CAZy_relab.tsv
humann2_renorm_table --input Travel004_CAZy.tsv -u relab --output Travel004_CAZy_relab.tsv
humann2_renorm_table --input Travel005_CAZy.tsv -u relab --output Travel005_CAZy_relab.tsv
humann2_renorm_table --input Travel006_CAZy.tsv -u relab --output Travel006_CAZy_relab.tsv
humann2_renorm_table --input Travel007_CAZy.tsv -u relab --output Travel007_CAZy_relab.tsv
humann2_renorm_table --input Travel008_CAZy.tsv -u relab --output Travel008_CAZy_relab.tsv
humann2_renorm_table --input Travel009_CAZy.tsv -u relab --output Travel009_CAZy_relab.tsv
humann2_renorm_table --input Travel010_CAZy.tsv -u relab --output Travel010_CAZy_relab.tsv
humann2_renorm_table --input Travel011_CAZy.tsv -u relab --output Travel011_CAZy_relab.tsv
humann2_renorm_table --input Travel012_CAZy.tsv -u relab --output Travel012_CAZy_relab.tsv
humann2_renorm_table --input Travel014_CAZy.tsv -u relab --output Travel014_CAZy_relab.tsv
humann2_renorm_table --input Travel015_CAZy.tsv -u relab --output Travel015_CAZy_relab.tsv
humann2_renorm_table --input Travel016_CAZy.tsv -u relab --output Travel016_CAZy_relab.tsv
humann2_renorm_table --input Travel017_CAZy.tsv -u relab --output Travel017_CAZy_relab.tsv
humann2_renorm_table --input Travel018_CAZy.tsv -u relab --output Travel018_CAZy_relab.tsv
humann2_renorm_table --input Travel019_CAZy.tsv -u relab --output Travel019_CAZy_relab.tsv
humann2_renorm_table --input Travel020_CAZy.tsv -u relab --output Travel020_CAZy_relab.tsv
humann2_renorm_table --input Travel021_CAZy.tsv -u relab --output Travel021_CAZy_relab.tsv
humann2_renorm_table --input Travel022_CAZy.tsv -u relab --output Travel022_CAZy_relab.tsv
humann2_renorm_table --input Travel023_CAZy.tsv -u relab --output Travel023_CAZy_relab.tsv
humann2_renorm_table --input Travel024_CAZy.tsv -u relab --output Travel024_CAZy_relab.tsv
humann2_renorm_table --input Travel025_CAZy.tsv -u relab --output Travel025_CAZy_relab.tsv
humann2_renorm_table --input Travel026_CAZy.tsv -u relab --output Travel026_CAZy_relab.tsv
humann2_renorm_table --input Travel027_CAZy.tsv -u relab --output Travel027_CAZy_relab.tsv
humann2_renorm_table --input Travel028_CAZy.tsv -u relab --output Travel028_CAZy_relab.tsv
humann2_renorm_table --input Travel030_CAZy.tsv -u relab --output Travel030_CAZy_relab.tsv
humann2_renorm_table --input Travel031_CAZy.tsv -u relab --output Travel031_CAZy_relab.tsv
humann2_renorm_table --input Travel033_CAZy.tsv -u relab --output Travel033_CAZy_relab.tsv
humann2_renorm_table --input Travel036_CAZy.tsv -u relab --output Travel036_CAZy_relab.tsv
humann2_renorm_table --input Travel037_CAZy.tsv -u relab --output Travel037_CAZy_relab.tsv
humann2_renorm_table --input Travel038_CAZy.tsv -u relab --output Travel038_CAZy_relab.tsv
humann2_renorm_table --input Travel039_CAZy.tsv -u relab --output Travel039_CAZy_relab.tsv
humann2_renorm_table --input Travel040_CAZy.tsv -u relab --output Travel040_CAZy_relab.tsv
humann2_renorm_table --input Travel041_CAZy.tsv -u relab --output Travel041_CAZy_relab.tsv
humann2_renorm_table --input Travel042_CAZy.tsv -u relab --output Travel042_CAZy_relab.tsv
humann2_renorm_table --input Travel043_CAZy.tsv -u relab --output Travel043_CAZy_relab.tsv
humann2_renorm_table --input Travel045_CAZy.tsv -u relab --output Travel045_CAZy_relab.tsv
humann2_renorm_table --input Travel046_CAZy.tsv -u relab --output Travel046_CAZy_relab.tsv
humann2_renorm_table --input Travel047_CAZy.tsv -u relab --output Travel047_CAZy_relab.tsv
humann2_renorm_table --input Travel048_CAZy.tsv -u relab --output Travel048_CAZy_relab.tsv
humann2_renorm_table --input Travel049_CAZy.tsv -u relab --output Travel049_CAZy_relab.tsv
humann2_renorm_table --input Travel050_CAZy.tsv -u relab --output Travel050_CAZy_relab.tsv
humann2_renorm_table --input Travel051_CAZy.tsv -u relab --output Travel051_CAZy_relab.tsv
humann2_renorm_table --input Travel052_CAZy.tsv -u relab --output Travel052_CAZy_relab.tsv
humann2_renorm_table --input Travel053_CAZy.tsv -u relab --output Travel053_CAZy_relab.tsv
humann2_renorm_table --input Travel054_CAZy.tsv -u relab --output Travel054_CAZy_relab.tsv
humann2_renorm_table --input Travel057_CAZy.tsv -u relab --output Travel057_CAZy_relab.tsv
humann2_renorm_table --input Travel058_CAZy.tsv -u relab --output Travel058_CAZy_relab.tsv
humann2_renorm_table --input Travel059_CAZy.tsv -u relab --output Travel059_CAZy_relab.tsv
humann2_renorm_table --input Travel060_CAZy.tsv -u relab --output Travel060_CAZy_relab.tsv
humann2_renorm_table --input Travel061_CAZy.tsv -u relab --output Travel061_CAZy_relab.tsv
humann2_renorm_table --input Travel062_CAZy.tsv -u relab --output Travel062_CAZy_relab.tsv
humann2_renorm_table --input Travel063_CAZy.tsv -u relab --output Travel063_CAZy_relab.tsv
humann2_renorm_table --input Travel064_CAZy.tsv -u relab --output Travel064_CAZy_relab.tsv
humann2_renorm_table --input Travel065_CAZy.tsv -u relab --output Travel065_CAZy_relab.tsv
humann2_renorm_table --input Travel066_CAZy.tsv -u relab --output Travel066_CAZy_relab.tsv
humann2_renorm_table --input Travel067_CAZy.tsv -u relab --output Travel067_CAZy_relab.tsv
humann2_renorm_table --input Travel068_CAZy.tsv -u relab --output Travel068_CAZy_relab.tsv
humann2_renorm_table --input Travel070_CAZy.tsv -u relab --output Travel070_CAZy_relab.tsv
humann2_renorm_table --input Travel071_CAZy.tsv -u relab --output Travel071_CAZy_relab.tsv
humann2_renorm_table --input Travel072_CAZy.tsv -u relab --output Travel072_CAZy_relab.tsv
humann2_renorm_table --input Travel073_CAZy.tsv -u relab --output Travel073_CAZy_relab.tsv
humann2_renorm_table --input Travel075_CAZy.tsv -u relab --output Travel075_CAZy_relab.tsv
humann2_renorm_table --input Travel076_CAZy.tsv -u relab --output Travel076_CAZy_relab.tsv
humann2_renorm_table --input Travel077_CAZy.tsv -u relab --output Travel077_CAZy_relab.tsv
humann2_renorm_table --input Travel078_CAZy.tsv -u relab --output Travel078_CAZy_relab.tsv
humann2_renorm_table --input Travel079_CAZy.tsv -u relab --output Travel079_CAZy_relab.tsv
humann2_renorm_table --input Travel080_CAZy.tsv -u relab --output Travel080_CAZy_relab.tsv
humann2_renorm_table --input Travel081_CAZy.tsv -u relab --output Travel081_CAZy_relab.tsv
humann2_renorm_table --input Travel082_CAZy.tsv -u relab --output Travel082_CAZy_relab.tsv
humann2_renorm_table --input Travel083_CAZy.tsv -u relab --output Travel083_CAZy_relab.tsv
humann2_renorm_table --input Travel084_CAZy.tsv -u relab --output Travel084_CAZy_relab.tsv
humann2_renorm_table --input Travel085_CAZy.tsv -u relab --output Travel085_CAZy_relab.tsv
humann2_renorm_table --input Travel086_CAZy.tsv -u relab --output Travel086_CAZy_relab.tsv
humann2_renorm_table --input Travel087_CAZy.tsv -u relab --output Travel087_CAZy_relab.tsv
humann2_renorm_table --input Travel088_CAZy.tsv -u relab --output Travel088_CAZy_relab.tsv
humann2_renorm_table --input Travel089_CAZy.tsv -u relab --output Travel089_CAZy_relab.tsv
humann2_renorm_table --input Travel090_CAZy.tsv -u relab --output Travel090_CAZy_relab.tsv
humann2_renorm_table --input Travel091_CAZy.tsv -u relab --output Travel091_CAZy_relab.tsv
humann2_renorm_table --input Travel092_CAZy.tsv -u relab --output Travel092_CAZy_relab.tsv
humann2_renorm_table --input Travel093_CAZy.tsv -u relab --output Travel093_CAZy_relab.tsv
humann2_renorm_table --input Travel095_CAZy.tsv -u relab --output Travel095_CAZy_relab.tsv
humann2_renorm_table --input Travel096_CAZy.tsv -u relab --output Travel096_CAZy_relab.tsv
humann2_renorm_table --input Travel097_CAZy.tsv -u relab --output Travel097_CAZy_relab.tsv
humann2_renorm_table --input Travel098_CAZy.tsv -u relab --output Travel098_CAZy_relab.tsv
humann2_renorm_table --input Travel099_CAZy.tsv -u relab --output Travel099_CAZy_relab.tsv
humann2_renorm_table --input Travel100_CAZy.tsv -u relab --output Travel100_CAZy_relab.tsv
humann2_renorm_table --input Travel101_CAZy.tsv -u relab --output Travel101_CAZy_relab.tsv
humann2_renorm_table --input Travel102_CAZy.tsv -u relab --output Travel102_CAZy_relab.tsv
humann2_renorm_table --input Travel103_CAZy.tsv -u relab --output Travel103_CAZy_relab.tsv
humann2_renorm_table --input Travel104_CAZy.tsv -u relab --output Travel104_CAZy_relab.tsv
humann2_renorm_table --input Travel105_CAZy.tsv -u relab --output Travel105_CAZy_relab.tsv
humann2_renorm_table --input Travel106_CAZy.tsv -u relab --output Travel106_CAZy_relab.tsv
humann2_renorm_table --input Travel107_CAZy.tsv -u relab --output Travel107_CAZy_relab.tsv
humann2_renorm_table --input Travel108_CAZy.tsv -u relab --output Travel108_CAZy_relab.tsv
humann2_renorm_table --input Travel109_CAZy.tsv -u relab --output Travel109_CAZy_relab.tsv
humann2_renorm_table --input Travel110_CAZy.tsv -u relab --output Travel110_CAZy_relab.tsv
humann2_renorm_table --input Travel111_CAZy.tsv -u relab --output Travel111_CAZy_relab.tsv
humann2_renorm_table --input Travel112_CAZy.tsv -u relab --output Travel112_CAZy_relab.tsv
humann2_renorm_table --input Travel113_CAZy.tsv -u relab --output Travel113_CAZy_relab.tsv
humann2_renorm_table --input Travel114_CAZy.tsv -u relab --output Travel114_CAZy_relab.tsv
humann2_renorm_table --input Travel115_CAZy.tsv -u relab --output Travel115_CAZy_relab.tsv
humann2_renorm_table --input Travel117_CAZy.tsv -u relab --output Travel117_CAZy_relab.tsv
humann2_renorm_table --input Travel118_CAZy.tsv -u relab --output Travel118_CAZy_relab.tsv
humann2_renorm_table --input Travel119_CAZy.tsv -u relab --output Travel119_CAZy_relab.tsv
humann2_renorm_table --input Travel120_CAZy.tsv -u relab --output Travel120_CAZy_relab.tsv
humann2_renorm_table --input Travel121_CAZy.tsv -u relab --output Travel121_CAZy_relab.tsv
humann2_renorm_table --input Travel122_CAZy.tsv -u relab --output Travel122_CAZy_relab.tsv
humann2_renorm_table --input Travel123_CAZy.tsv -u relab --output Travel123_CAZy_relab.tsv
humann2_renorm_table --input Travel124_CAZy.tsv -u relab --output Travel124_CAZy_relab.tsv
humann2_renorm_table --input Travel125_CAZy.tsv -u relab --output Travel125_CAZy_relab.tsv
humann2_renorm_table --input Travel126_CAZy.tsv -u relab --output Travel126_CAZy_relab.tsv
humann2_renorm_table --input Travel131_CAZy.tsv -u relab --output Travel131_CAZy_relab.tsv
